### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by shannonMG** [shannonMG/prework-study-guide#1]
# HTML

## User Story
As a bootcamp student,
I want the prework notes to be structured on a webpage,
so that I can easily find and read information

## Acceptance Criteria
GIVEN a Prework Study Guide Website,
WHEN I visit the website in my browser,
THEN I see four boxed titled HTML, CSS, Git, and JavaScript with associated notes listed.

**Comment by PrasannaKatabattini** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prework Study Guide</title>
    <style>
        /* Basic styling for the boxes */
        .box {
            border: 1px solid #ccc;
            padding: 20px;
            margin: 20px;
            width: 300px;
            float: left;
        }
    </style>
</head>
<body>
    <div class="box">
        <h2>HTML</h2>
        <p>Notes on HTML...</p>
    </div>
    <div class="box">
        <h2>CSS</h2>
        <p>Notes on CSS...</p>
    </div>
    <div class="box">
        <h2>Git</h2>
        <p>Notes on Git...</p>
    </div>
    <div class="box">
        <h2>JavaScript</h2>
        <p>Notes on JavaScript...</p>
    </div>
</body>
</html>
